# Generated by Django 2.2.4 on 2019-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='parte',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
