# Generated by Django 2.2.4 on 2019-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_entrada_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='capitulo',
            field=models.IntegerField(),
        ),
    ]
